# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'UIComponents' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
	
  # Pods for UIComponents
  pod 'R.swift', '~>7.3.2'
  pod 'ReachabilitySwift', '~>5.0.0'
  pod 'Alamofire', '~>5.7.0'
end
